server:
  port: 8999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"










